### ISSUE TITLE
io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact

### ISSUE THREAD

**Issue by loghijiaha** [Loghijiaha/ipython#2]
This following Jenkins Builder UI works fine. When I apply the configurations it fails.
![Screenshot from 2020-01-19 03-03-59](https://user-images.githubusercontent.com/36206296/72670907-4b729900-3a69-11ea-9011-8d8188de5ee8.png)

The following error continues after remodifying the POM with okhttp.

![Screenshot from 2020-01-19 03-04-08](https://user-images.githubusercontent.com/36206296/72670865-d010e780-3a68-11ea-81e5-74ade3198d89.png)

**Comment by vinayak-tyagi** [comment]
![image](https://user-images.githubusercontent.com/39195953/76705855-4482a280-6709-11ea-9242-ad281d7af98c.png)
link to page:- https://zeppelin.apache.org/docs/0.8.2/interpreter/python.html#ipython-support 
I think this might help you!

**Comment by loghijiaha** [comment]
I already have resolved it. Thank you @vinayak-tyagi
